/**
 * Canonical site + business facts — the single place to change them.
 *
 * Everything here feeds SEO output (canonical URLs, Open Graph, structured
 * data), so a wrong value is duplicated across every page rather than being a
 * one-off cosmetic bug. Values are drawn from what the site already states in
 * its footer and rental agreement; nothing here is invented.
 *
 * Set VITE_SITE_URL at build time when the domain changes. It must be absolute
 * and have no trailing slash: social scrapers reject relative og:image paths,
 * and Google treats http/https and www/non-www as different canonical hosts.
 */
export const SITE_URL = (
  import.meta.env.VITE_SITE_URL ?? "https://drive-smart-tx.lovable.app"
).replace(/\/+$/, "");

/** Absolute URL for a site-relative path — required for og:image and canonical. */
export function absoluteUrl(path = "/"): string {
  return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;
}

export const BUSINESS = {
  name: "Royalty Luxury Transportation Services",
  /** Short form for titles, where the full legal name eats the character budget. */
  shortName: "Royalty Luxury",
  phone: "+1-614-359-1370",
  phoneDisplay: "(614) 359-1370",
  email: "royaltylux8@gmail.com",
  city: "Dallas",
  region: "TX",
  regionName: "Texas",
  postalCode: "75235",
  country: "US",
  minAge: 25,
} as const;

/** Social/OG share card. Generated by scripts/generate-og-image.py. */
export const OG_IMAGE = {
  path: "/og-image.png",
  width: 1200,
  height: 630,
  alt: `${BUSINESS.name} — economy car and premium SUV rentals in ${BUSINESS.city}, ${BUSINESS.regionName}`,
} as const;

/**
 * Cities the rental serves, used for areaServed in structured data.
 * Kept to the DFW metro the footer already claims — not padded with towns the
 * business does not actually serve, which reads as spam to search engines.
 */
export const SERVICE_AREA = [
  "Dallas",
  "Fort Worth",
  "Irving",
  "Arlington",
  "Plano",
  "Garland",
  "Grand Prairie",
  "Richardson",
  "Mesquite",
  "Carrollton",
] as const;
